server:
  port: 80
property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c
fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green
datasource:
  url: jdbc:h2:mem:testdb
spring:
  h2:
    console:
      enabled: true
---
spring:
  profiles: local
server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: real
server:
  port: 8082