spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/MyDB?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api # API의 모든 요청의 기본 경로 지정
      default-page-size: 10 # 클라이언트가 따로 페이지 크기를 요청하지 않았을 때 적용할 기본 페이지 크기 설정
      max-page-size: 10 # 최대 페이지 수 설정

server:
  port: 8081