spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
server:
  port: 8081