server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

spring:
  h2:
    console:
      enable: true
  jpa:
    show-sql: true
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:mem:testdb
  security:
    user:
      name: hottj
      password : "0000"
management:
  endpoints:
    web:
      exposure:
        include: "*"